import { Profile } from '@/types/antimicro';
import { getAntiMicroXCode } from '@/utils/keyMap';
// Mapping from internal ControllerButtonId to AntiMicroX button IDs
const BUTTON_ID_MAP: Record<string, string> = {
  'A': 'a',
  'B': 'b',
  'X': 'x',
  'Y': 'y',
  'LB': 'leftshoulder',
  'RB': 'rightshoulder',
  'LT': 'lefttrigger',
  'RT': 'righttrigger',
  'Back': 'back',
  'Start': 'start',
  'Guide': 'guide',
  'LS': 'leftstick',
  'RS': 'rightstick',
  'DPadUp': 'dpup',
  'DPadDown': 'dpdown',
  'DPadLeft': 'dpleft',
  'DPadRight': 'dpright',
  'P1': 'paddle1',
  'P2': 'paddle2',
  'P3': 'paddle3',
  'P4': 'paddle4',
};
const escapeXml = (unsafe: string): string => {
  return unsafe.replace(/[<>&'"]/g, (c) => {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '\'': return '&apos;';
      case '"': return '&quot;';
      default: return c;
    }
  });
};
export const generateAntiMicroXXML = (profile: Profile, actions: {id: string, defaultKey: string}[]): string => {
  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += '<!-- Generated by TacticalBind -->\n';
  xml += '<gamecontroller configversion="19" appversion="3.3.3">\n';
  xml += '    <sdl2gamecontroller>\n';
  profile.sets.forEach((set, index) => {
    xml += `        <set index="${index + 1}">\n`;
    xml += `            <name>${escapeXml(set.name)}</name>\n`;
    // 1. Export Axis Deadzones (if any)
    // AntiMicroX expects axis definitions inside the set
    if (profile.deadzones) {
      Object.entries(profile.deadzones).forEach(([axis, value]) => {
        if (value > 0) {
          xml += `            <axis id="${axis}">\n`;
          xml += `                <deadZone>${value}</deadZone>\n`;
          xml += `            </axis>\n`;
        }
      });
    }
    // 2. Export Button Mappings
    // Filter buttons that have at least one slot assigned
    const activeMappings = Object.values(set.mappings).filter(m => 
      m.slots.some(s => s.actionId || s.macroId || s.modeShiftId)
    );
    activeMappings.forEach(mapping => {
      const antiMicroId = BUTTON_ID_MAP[mapping.id];
      if (!antiMicroId) return;
      xml += `            <button id="${antiMicroId}">\n`;
      xml += `                <slots>\n`;
      mapping.slots.forEach((slot) => {
        if (!slot) return;
        // Check if slot has content
        const hasContent = slot.actionId || slot.macroId || slot.modeShiftId;
        if (!hasContent) return;
        xml += `                    <slot>\n`;
        if (slot.modeShiftId) {
          const targetSetIndex = profile.sets.findIndex(s => s.id === slot.modeShiftId);
          if (targetSetIndex !== -1) {
            xml += `                        <setselect>${targetSetIndex + 1}</setselect>\n`;
          }
        } else if (slot.macroId) {
          const macro = profile.macros.find(m => m.id === slot.macroId);
          if (macro) {
            macro.steps.forEach(step => {
              if (step.type === 'delay') {
                xml += `                        <event type="delay" value="${step.value}"/>\n`;
              } else if (step.type === 'key') {
                const mapping = getAntiMicroXCode(String(step.value));
                xml += `                        <event type="key" value="${mapping.code}"/>\n`;
              } else if (step.type === 'mouse') {
                 const mapping = getAntiMicroXCode(String(step.value));
                 xml += `                        <event type="mouse" value="${mapping.code}"/>\n`;
              }
            });
          }
        } else if (slot.actionId) {
          const action = actions.find(a => a.id === slot.actionId);
          if (action) {
            const mapping = getAntiMicroXCode(action.defaultKey);
            xml += `                        <code>${mapping.code}</code>\n`;
            xml += `                        <mode>${mapping.mode}</mode>\n`;
          }
        }
        xml += `                    </slot>\n`;
      });
      xml += `                </slots>\n`;
      xml += `            </button>\n`;
    });
    xml += `        </set>\n`;
  });
  xml += '    </sdl2gamecontroller>\n';
  xml += '</gamecontroller>';
  return xml;
};